use_frameworks!
target 'APIFire_Tests' do
  pod 'APIFire', :path => '../'
  
  pod 'Quick', '~> 6.1'
  pod 'Nimble', '~> 11.2'
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
